name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download OC
        run: curl -L -o openshift-client-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.18/openshift-client-linux.tar.gz
      - name: tar.gz
        run: tar -vzxf openshift-client-linux.tar.gz
      - name: Docker Login registry.redhat.io
        run: echo ${{ secrets.REGISTRY_REDHAT_PASSWORD }} | docker login registry.redhat.io -u ${{ secrets.REGISTRY_REDHAT_USERNAME }} --password-stdin
      - name: Docker Login quay.io
        run: echo ${{ secrets.REGISTRY_QUAY_PASSWORD }} | docker login quay.io -u danielmenezesbr --password-stdin
      - name: Build Image
        run: |
          export TAG_NAME=$(python3 -c 'import uuid; from datetime import datetime; print(datetime.now().strftime("%Y-%m-%d") + "_" + str(uuid.uuid4()))')
          echo $TAG_NAME
          ./oc adm catalog build --appregistry-org redhat-operators \
            --from=registry.redhat.io/openshift4/ose-operator-registry:v4.6 \
            --to=quay.io/danielmenezesbr/repotest:$TAG_NAME-snapshot-OCPv4.6 \
            --filter-by-os="linux/amd64" --insecure
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - name: Test Image
        run: |
          export TAG_NAME=${{ env.TAG_NAME }}
          docker pull quay.io/danielmenezesbr/repotest:$TAG_NAME-snapshot-OCPv4.6
          docker run -p 50051:50051 quay.io/danielmenezesbr/repotest:$TAG_NAME-snapshot-OCPv4.6 &
          sleep 10
          export ID=$(docker ps | grep 'quay' | awk '{ print $1 }')
          echo "ID: $ID"
          export IP=$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $ID)
          echo "CATALOG IP: $IP"
          docker run fullstorydev/grpcurl -plaintext -d '{"pkgName":"servicemeshoperator","channelName":"stable"}' $IP:50051 api.Registry/GetBundleForChannel | grep csvName
          
